%{

This is the production script that is used to generate all the 
    result images.
It goes through the folder of images generated by initScript
    and individually segments each image, putting the result
    into a different folder.

%}


firstImage = im2double(imread('rabbitImages/image1.jpg'));
sizeImage = size(firstImage);
height = sizeImage(1);
width = sizeImage(2);

numImages = 50;
index = 1;

for num = 1:numImages
    
    imname = strcat('rabbitImages/image',num2str(num),'.jpg');
    image1 = im2double(imread(imname));

    %calls the getSegImage.m function
    image1Seg = getSegImage(image1);
    
    imnameWrite = strcat('resultImages/image',num2str(num),'.jpg');
    imwrite(image1Seg,imnameWrite,'JPEG');
    
end


